### PR TITLE
feat: Add situations to departures v2 query responses

### PR DESCRIPTION
**Pull request by gorandalum**
Also some additional updates from Entur were added when the graphql types were regenerated.

Resolves https://github.com/AtB-AS/kundevendt/issues/147

### CODE REVIEW

**Review by rosvik — APPROVED** [review]

**Comment by gorandalum** [comment]
Changed to using the shared situation fragment. I rerequested review @rosvik.

**Comment by rosvik** [comment]
@gorandalum Should we add the situation fragment to trip legs as well, or is there a reason not to? [Here](https://github.com/AtB-AS/atb-bff/pull/183/files#diff-d8d5dc9492ba205ccf786e87823dba47eb7dbdc7fbc8340650b86dafef1aee6cR56-R61)

**Comment by rosvik** [comment]
@toretefre Not sure if this is useful to what you're working on, but maybe have a look if it is?

**Comment by toretefre** [comment]
Seems to be the notices of servicejourneys that is missing for my part, @rosvik: https://github.com/AtB-AS/kundevendt/issues/2881

**Review by rosvik — APPROVED** [review]
LGTM 👍 Will you make an update to the app with new types as well?

**Pull request merged**
