### PR TITLE
test: add app version to API tests

### PR DESCRIPTION
**Pull request by tormoseng**
The API-tests was missing app version.

### CODE REVIEW

**Review by reidzeibel — APPROVED** [review]
Do we have to update versions manually in the future on every release, or is it just occassionally?

**Comment by tormoseng** [comment]
> Do we have to update versions manually in the future on every release, or is it just occassionally?

Just occassionally. The important part is to update when we update the `MIN_APP_VERSION` ENV param for the BFF. We will before December increase it to `1.53.1`, but I guess `1.58` will last a year 😊

**Comment by reidzeibel** [comment]
Could we somehow pass the `MIN_APP_VERSION` into that api test part? 🤔 seems like an easier way to not lost track when it is updated

**Comment by tormoseng** [comment]
> Could we somehow pass the MIN_APP_VERSION into that api test part? 🤔 seems like an easier way to not lost track when it is updated

True. I can look into it 😊

**Comment by gorandalum** [comment]
Note that tests should then test the `MIN_APP_VERSION` feature, not test the specific min app version set for the bff in production.

**Pull request merged**
