### PR TITLE
Vechicles api endpoint

### PR DESCRIPTION
**Pull request by KristianSelnas**

### CODE REVIEW

**Review by gorandalum — COMMENTED** [review]
Looks good! Some comments that are not directly related to your changes. 

When we now have a "fresh start" with the mobility endpoints, I think we can do some improvements over the existing journey-planner endpoints. These suggestions are based on our experiences over the last couple of years with the bff.

- **More use of fragments.** Generally whatever entity that we want to have a type for in the app should have its own fragment. I think in this PR it would be nice to have a `VehicleFragment`, and maybe even `SystemFragment` and `PricingPlanFragment`. 
- **Nested fragments in the generated code**. Now in the generated code all nested fragments are inlined in the generated query/fragment. This is the default behaviour. For example the generated type for `GetVehiclesQuery` does not include `TranslationFragment` or `PricingSegmentFragment`. I think it would be nice to get the actual fragment types also on the nested fragments, and this should be possible by setting [`inlineFragmentTypes` to `combine`](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-operations#inlinefragmenttypes) in the codegen.yml.

@rosvik Also have done quite a bit of work in the BFF, so I added him to the PR. Maybe he has some nice suggestions, or maybe disagrees with my suggestions. 😅

**Review by rosvik — APPROVED** [review]
This looks good indeed! I agree with Gøran, it would be nice to have nested fragments not be inline, which should make typing in the app more easy to work with. Maybe better to do as it's own PR tho?

Also, if you use [conventional commit formatting](https://www.conventionalcommits.org/en/v1.0.0/) for PR titles, the generated changelog should work better when we make a release. (So something like `feat: add vehicles api endpoint`)

**Comment by KristianSelnas** [comment]
Can you take a look now, @gorandalum ?

**Comment by KristianSelnas** [comment]
I've extracted a `VehicleFragment` now

**Comment by rosvik** [comment]
@KristianSelnas Is this ready to merge? Would be good to not have this branch live too long, since it touches so many files.

**Comment by KristianSelnas** [comment]
@rosvik I'll merge it now.

**Pull request merged**
